'''
problem: Even Fib Sum

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
def fibSum(max):
	ans = 0
	x = 1  # Represents the current Fibonacci number being processed
	y = 2  # Represents the next Fibonacci number in the sequence
	while x <= max:
		if x % 2 == 0:	# only consider fib #'s that are even
			ans += x
		x, y = y, x + y
	return str(ans)

    


def main():
	print('this program finds the sum of the Fibonacci sequence for those values who do not exceed 4 million')
	
	print(fibSum(4000000))



main()